from flask import Flask, request, send_file, render_template
from reportlab.platypus import SimpleDocTemplate, Paragraph, Image, Spacer
from reportlab.platypus import HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os
from PIL import Image as PILImage, ImageDraw
from flask import after_this_request
import shutil

app = Flask(__name__)

# ---------- IMAGE PROCESSING ----------
def process_hero_image(input_path, output_path):
    img = PILImage.open(input_path).convert("RGB")
    width, height = img.size

    target_ratio = 16 / 6
    new_height = int(width / target_ratio)

    if new_height < height:
        top = (height - new_height) // 2
        img = img.crop((0, top, width, top + new_height))
    else:
        new_width = int(height * target_ratio)
        left = (width - new_width) // 2
        img = img.crop((left, 0, left + new_width, height))

    img = img.resize((1000, 375))

    radius = 30
    mask = PILImage.new("L", img.size, 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle([(0, 0), img.size], radius=radius, fill=255)

    img.putalpha(mask)

    bg = PILImage.new("RGB", img.size, (255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    bg.save(output_path)

    return output_path


# ---------- TEMP FOLDER ----------
if not os.path.exists("temp"):
    os.makedirs("temp")


# ---------- HOME ----------
@app.route('/')
def home():
    return render_template('index.html')


# ---------- PDF EXPORT ----------
@app.route('/export-pdf', methods=['POST'])
def export_pdf():

    doc = SimpleDocTemplate(
        "blog.pdf",
        rightMargin=40,
        leftMargin=40,
        topMargin=25,
        bottomMargin=25
    )

    elements = []

    # ----- STYLES -----
    title_style = ParagraphStyle(
        name='Title',
        fontSize=30,
        leading=36,
        textColor=colors.HexColor("#1e3a8a"),
        alignment=TA_CENTER,
        spaceAfter=18
    )

    desc_style = ParagraphStyle(
        name='Desc',
        fontSize=13,
        leading=20,
        textColor=colors.HexColor("#6b7280"),
        alignment=TA_CENTER,
        spaceAfter=25
    )

    heading_style = ParagraphStyle(
        name='Heading',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#2563eb"),
        spaceBefore=10,
        spaceAfter=8
    )

    content_style = ParagraphStyle(
        name='Content',
        fontSize=13,
        leading=21,
        textColor=colors.HexColor("#111827"),
        spaceAfter=16
    )

    # ----- DATA -----
    title = request.form.get("title")
    desc = request.form.get("description")
    hero = request.files.get("hero")

    # ----- HERO IMAGE -----
    if hero and hero.filename:
        original = f"temp/original_{hero.filename}"
        processed = f"temp/processed_{hero.filename}"

        hero.save(original)
        process_hero_image(original, processed)

        img = Image(processed, width=520, height=200)
        img.hAlign = 'CENTER'
        elements.append(img)
        elements.append(Spacer(1, 10))

    # ----- TITLE + DESC -----
    elements.append(Paragraph(title, title_style))
    elements.append(Paragraph(desc, desc_style))

    # ----- SECTIONS -----
    i = 0
    while True:
        heading = request.form.get(f"heading_{i}")
        content = request.form.get(f"content_{i}")
        image = request.files.get(f"image_{i}")

        if not heading and not content:
            break

        elements.append(Paragraph(heading, heading_style))

        if image:
            path = f"temp/{image.filename}"
            image.save(path)

            img = Image(path)

            max_width = 320
            if img.imageWidth > max_width:
                ratio = max_width / img.imageWidth
                img.drawWidth = max_width
                img.drawHeight = img.imageHeight * ratio

            img.hAlign = 'CENTER'

            elements.append(Spacer(1, 8))
            elements.append(img)
            elements.append(Spacer(1, 16))

        elements.append(Paragraph(content, content_style))
        elements.append(Spacer(1, 10))

        i += 1

    # Footer
    def add_footer(canvas, doc):
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(300, 20, "Generated by HanuAi Blogs")

    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)
    @after_this_request
    def cleanup(response):
        try:
            shutil.rmtree("temp")
            os.makedirs("temp", exist_ok=True)
        except Exception as e:
            print("Cleanup error:", e)
        return response
    return send_file("blog.pdf", as_attachment=True)


# ---------- DOCX EXPORT ----------
@app.route('/export-docx', methods=['POST'])
def export_docx():

    doc = Document()

    title = request.form.get("title")
    desc = request.form.get("description")
    hero = request.files.get("hero")

    # TITLE
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title_para.add_run(title)
    run.font.size = Pt(30)
    run.font.bold = True
    run.font.color.rgb = RGBColor(30, 58, 138)

    # DESCRIPTION
    desc_para = doc.add_paragraph()
    desc_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = desc_para.add_run(desc)
    run.font.size = Pt(13)
    run.font.color.rgb = RGBColor(107, 114, 128)

    # HERO IMAGE
    if hero and hero.filename:
        path = f"temp/{hero.filename}"
        hero.save(path)
        doc.add_picture(path, width=Inches(5.8))

    doc.add_paragraph("────────────────────────────")

    # SECTIONS
    i = 0
    while True:
        heading = request.form.get(f"heading_{i}")
        content = request.form.get(f"content_{i}")
        image = request.files.get(f"image_{i}")

        if not heading and not content:
            break

        para = doc.add_paragraph()
        run = para.add_run(heading)
        run.font.size = Pt(18)
        run.font.bold = True
        run.font.color.rgb = RGBColor(37, 99, 235)

        para = doc.add_paragraph(content)
        para.paragraph_format.space_after = Pt(12)

        if image:
            path = f"temp/{image.filename}"
            image.save(path)
            doc.add_picture(path, width=Inches(5.5))

        i += 1

    # Footer
    section = doc.sections[0]
    footer = section.footer
    footer.paragraphs[0].text = "Generated by HanuAi Blogs"

    doc.save("blog.docx")

    return send_file("blog.docx", as_attachment=True)


# ---------- RUN ----------
if __name__ == '__main__':
    app.run(debug=True)